### ISSUE TITLE
luajit.io site is down

### ISSUE THREAD

**Issue by ogoudron** [kingluo/luajit.io#2]
Hello.
The http://luajit.io site is down.

**Comment by kingluo** [comment]
Yes, the site was down for a while.
Now I update the latest version and start it again.
Thanks for reminding.

**Comment by ogoudron** [comment]
i have used openresty some time ago and i love your idea with luajit.io.
Does your code is ready for some "limited production" test ?
Thanks too.

**Comment by kingluo** [comment]
This framework is considered experimental and still under active development (the luajit.io site is one simple example).
The functionalities are almost done, but there is still big room to improve the performance, especially at the coroutine part.
Here is some result sample from "hello world" benchmark:
ngx_lua 32k rps
luajit.io 24k rps
luajit.io 28k rps (without coroutine)

**Comment by ogoudron** [comment]
Thanks for your answer.
I will do some tests before using it.
