### ISSUE TITLE
Feature: Host on Terralang

### ISSUE THREAD

**Issue by rektide** [kingluo/luajit.io#8]
[Terralang](http://terralang.org/) is a language with an embedded LuaJIT. It has very nice runtime compilation capabilities and metaprogramming facilities, which makes it a good, fast programming environment.

I'd love to see a demo of Luajit.io running with Terra.

**Comment by rektide** [comment]
@zdevito is the author of Terra. Perhaps he has some idea for what might be needed to accomplish this.

**Comment by creationix** [comment]
That would be cool.  I'd be willing to try and see how hard it would be getting luvit.io running on terralang.
